version: "3.8"

services:
  # Service Frontend React avec Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stormy-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://20.75.167.214:8080/
      - VITE_WS_URL=http://20.75.167.214:8080/
    command: npm run dev
    stdin_open: true
    tty: true

networks:
  default:
    name: stormy-network
